services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=restaurant
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  restaurant.api:
    image: restaurant.api
    build:
      context: .
      dockerfile: src/Restaurant.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=restaurant;Username=postgres;Password=postgres
    depends_on:
      - db

volumes:
  postgres-data:
